Update spring.yml

diff --git a/.github/workflows/spring.yml b/.github/workflows/spring.yml
--- a/.github/workflows/spring.yml
+++ b/.github/workflows/spring.yml
@@ -27,18 +27,18 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
-          python-version: '3.11'
-          cache: pip
+          python-version: '3.12'
           architecture: x64
 
       # Cache Python shits
-      - name: Cache Python packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          if [ -f edge/requirements.txt ]; then
+            pip install -r edge/requirements.txt
+          else
+            echo "requirements.txt not found, skipping dependency installation"
+          fi
 
       # install Python ip tools
       - name: Install dependencies
@@ -50,18 +50,16 @@ jobs:
       - name: Run python
         run: python edge/spring.py
 
-      - name: Check changes
+      # Commit and push if chanes
+      - name: Commit and push if changed
         run: |
-          echo "Checking the changes made..."
-          git status
-          git add -A
-          git diff --quiet && git diff --staged --quiet || git commit -m "Task done"
-
-      - name: Commit and push files
-        uses: EndBug/add-and-commit@v7
-        with:
-          author_name: 'Github Actions'
-          author_email: 'actions@github.com'
-          push: 'https://github.com/Diana-Cl/vless.git'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          git config --local user.name "Diana-Cl"
+          git config --local user.email "135276904+Diana-Cl@users.noreply.github.com"
+          git add *.json
+          git diff --quiet && git diff --staged --quiet || (
+            git commit -m "Task done $(TZ='Asia/Tehran' date '+%H:%M:%S')" -m "wireuard private key, addresses, reserved and all IPs have been renewed"
+            git -c committer.name="CI Bot" -c committer.email="ci@example.com" \
+                commit --amend --no-edit
+          )
+          git push
+          
